[package]
name = "taste-voice"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
sha2.workspace = true
hyper.workspace = true
hyper-util.workspace = true
hyper-rustls.workspace = true
rustls.workspace = true
http-body-util.workspace = true
http.workspace = true
bytes.workspace = true
whisper-rs.workspace = true
gstreamer.workspace = true
gstreamer-app.workspace = true

[dev-dependencies]
tempfile = "3"
