//! Agent confinement via bubblewrap.
//!
//! Threat model: **neither the agent nor the project repo is trusted.**
//! Agents are host-side processes (they must survive devcontainer reloads),
//! but they never get the host. Every agent subprocess runs under `bwrap`
//! with:
//!
//! - the OS visible read-only (toolchains, certs, DNS keep working),
//! - a tmpfs over `$HOME` — no general home-directory access, ever — with
//!   only the agent's own auth/config paths bound back in,
//! - a tmpfs over `$XDG_RUNTIME_DIR` and `/tmp`, hiding the session D-Bus
//!   socket (which could otherwise reach the Flatpak portal → host exec),
//!   the Wayland/X11 sockets, and everything else that lives there; only
//!   the IDE's MCP socket is bound back in,
//! - the workspace bound read-write in container mode, or read-only with
//!   only the devcontainer scope writable in safe mode,
//! - `.git/hooks` masked and `.git/config` read-only, so an agent cannot
//!   plant hooks or `core.fsmonitor` commands that the *user's* next
//!   host-side git invocation would execute,
//! - network shared (agents need their APIs; fetching public remotes works).
//!
//! Remote git is read-only by construction: the tmpfs home contains no ssh
//! keys and no credential helpers, so authenticated push is impossible. The
//! `GIT_CONFIG_GLOBAL` push-block below is defense-in-depth and UX (a clear
//! error instead of an auth prompt), not the enforcement — an agent
//! controls its own environment inside the sandbox.
//!
//! Known residual risk, accepted and documented: agents have network access,
//! so a hostile agent could exfiltrate *workspace contents*. Confinement
//! bounds what it can read to the workspace and its own config — not what
//! it can say.
//!
//! If bubblewrap is unavailable, agents do not launch. Confinement is not
//! best-effort.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::AgentSpec;

/// Git config that blocks pushing while leaving fetch untouched.
/// `pushInsteadOf` rewrites only push URLs; the schemes below cover https,
/// ssh, git and scp-style remotes.
const GIT_PUSH_BLOCK: &str = "\
# Generated by taste-ide: agents may fetch/pull but never push.
[url \"push-blocked://\"]
\tpushInsteadOf = https://
[url \"push-blocked-ssh://\"]
\tpushInsteadOf = ssh://
[url \"push-blocked-git://\"]
\tpushInsteadOf = git://
[url \"push-blocked-scp://\"]
\tpushInsteadOf = git@
";

/// Where the push-block gitconfig lives; written once per run. Deliberately
/// *outside* `XDG_RUNTIME_DIR` (which is masked in the sandbox): it sits in
/// the IDE's cache dir and is bound in read-only.
pub fn ensure_git_policy_file() -> Result<PathBuf> {
    let base = std::env::var("XDG_CACHE_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
            Path::new(&home).join(".cache")
        })
        .join("taste-ide");
    std::fs::create_dir_all(&base).context("creating taste-ide cache dir")?;
    let path = base.join("agent-gitconfig");
    std::fs::write(&path, GIT_PUSH_BLOCK).context("writing agent git policy file")?;
    Ok(path)
}

/// The URL bridge: how a sandboxed agent's sign-in flow reaches the user's
/// real browser. The sandbox has no D-Bus and no portal, so `xdg-open`
/// cannot work inside it — instead `$BROWSER` points at a helper that
/// writes the URL into a directory the IDE watches. The IDE confirms with
/// the user and opens it host-side. OAuth localhost callbacks work because
/// the sandbox shares the network namespace.
pub fn url_bridge_dir() -> PathBuf {
    let base = std::env::var("XDG_CACHE_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
            Path::new(&home).join(".cache")
        });
    base.join("taste-ide").join("agent-urls")
}

/// Write the `$BROWSER` helper script and create the URL drop directory.
/// Returns (script path, drop dir).
pub fn ensure_url_bridge() -> Result<(PathBuf, PathBuf)> {
    let dir = url_bridge_dir();
    std::fs::create_dir_all(&dir).context("creating agent-urls dir")?;
    let script_path = dir
        .parent()
        .unwrap_or(Path::new("/tmp"))
        .join("taste-open-url");
    let script = format!(
        "#!/bin/sh\n# Generated by taste-ide: forwards URLs from sandboxed agents\n\
         # to the IDE, which confirms with the user before opening.\n\
         umask 077\nprintf '%s\\n' \"$1\" > \"{}/url-$$\"\n",
        dir.display()
    );
    std::fs::write(&script_path, script).context("writing url helper")?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&script_path, std::fs::Permissions::from_mode(0o755))
            .context("marking url helper executable")?;
    }
    Ok((script_path, dir))
}

/// True when the IDE itself runs inside a container (the self-hosting
/// bootstrap: taste-ide launched from its own devcontainer). bwrap cannot
/// nest in a rootless container, and it doesn't need to: the container is
/// the confinement — the user's real home is not mounted there at all.
pub fn inside_container() -> bool {
    Path::new("/run/.containerenv").exists() || Path::new("/.dockerenv").exists()
}

pub fn bwrap_available() -> bool {
    std::env::var_os("PATH")
        .map(|paths| std::env::split_paths(&paths).any(|dir| dir.join("bwrap").is_file()))
        .unwrap_or(false)
}

/// Wrap an agent command in the confinement sandbox.
///
/// `safe_mode` narrows workspace writes to the devcontainer scope.
/// `mcp_socket` is the one path under the masked runtime dir that is bound
/// back in, so the agent can reach the IDE's MCP server. The mount set is
/// fixed for the life of the process: a session spawned in safe mode keeps
/// safe-mode confinement until a new session is started.
/// Agent-in-a-container confinement: run the agent inside the project's
/// devcontainer image via (host) podman. Stronger than bwrap — no host
/// filesystem at all beyond the workspace and the IDE's bridge files —
/// and it is what makes the packaged Flatpak and bare-host runs work at
/// all: neither has node/npx installed.
///
/// Returns None when podman or the image is unavailable (bwrap fallback
/// applies). The availability probe runs once and is cached.
pub fn container_agent_command(
    spec: &AgentSpec,
    cwd: &Path,
    git_policy: &Path,
    mcp_socket: Option<&Path>,
    url_bridge: (&Path, &Path),
) -> Option<(String, Vec<String>)> {
    static AVAILABLE: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    let image =
        std::env::var("TASTE_AGENT_IMAGE").unwrap_or_else(|_| "taste-ide-devcontainer".to_string());
    let sandboxed = Path::new("/.flatpak-info").exists();
    let available = *AVAILABLE.get_or_init(|| {
        let mut check = if sandboxed {
            let mut c = std::process::Command::new("flatpak-spawn");
            c.args(["--host", "podman", "image", "exists", &image]);
            c
        } else {
            let mut c = std::process::Command::new("podman");
            c.args(["image", "exists", &image]);
            c
        };
        check
            .status()
            .map(|status| status.success())
            .unwrap_or(false)
    });
    if !available {
        return None;
    }

    let mut args: Vec<String> = Vec::new();
    if sandboxed {
        args.extend(["--host".into(), "podman".into()]);
    }
    args.extend(
        [
            "run",
            "--rm",
            "-i",
            "--userns=keep-id:uid=1000,gid=1000",
            "--security-opt",
            "label=disable",
            // OAuth callbacks reach the login flow.
            "--network=host",
            // Sign-ins persist across sessions, isolated from the real home.
            "-v",
            "taste-agent-home:/home/dev",
            "-e",
            "HOME=/home/dev",
        ]
        .map(String::from),
    );
    // The workspace mounts at its real path, so every path the agent and
    // the IDE exchange is valid on both sides.
    args.push("-v".into());
    args.push(format!("{}:{}", cwd.display(), cwd.display()));
    args.push("-w".into());
    args.push(cwd.display().to_string());
    args.push("-v".into());
    args.push(format!(
        "{}:{}:ro",
        git_policy.display(),
        git_policy.display()
    ));
    args.push("-e".into());
    args.push(format!("GIT_CONFIG_GLOBAL={}", git_policy.display()));
    if let Some(socket) = mcp_socket {
        args.push("-v".into());
        args.push(format!("{}:{}", socket.display(), socket.display()));
    }
    let (url_script, url_dir) = url_bridge;
    args.push("-v".into());
    args.push(format!("{}:{}", url_dir.display(), url_dir.display()));
    args.push("-v".into());
    args.push(format!(
        "{}:{}:ro",
        url_script.display(),
        url_script.display()
    ));
    args.push("-e".into());
    args.push(format!("BROWSER={}", url_script.display()));
    for (key, value) in &spec.env {
        args.push("-e".into());
        args.push(format!("{key}={value}"));
    }
    args.push(image);
    args.push(spec.command.clone());
    args.extend(spec.args.iter().cloned());
    let program = if sandboxed { "flatpak-spawn" } else { "podman" };
    Some((program.to_string(), args))
}

pub fn wrap(
    spec: &AgentSpec,
    workspace_root: &Path,
    safe_mode: bool,
    home: &Path,
    git_policy: &Path,
    mcp_socket: Option<&Path>,
    url_bridge: Option<(&Path, &Path)>,
) -> (String, Vec<String>) {
    let mut args: Vec<String> = vec![
        "--die-with-parent".into(),
        "--unshare-pid".into(),
        // OS read-only: node, git, certs, resolv.conf all keep working.
        "--ro-bind".into(),
        "/".into(),
        "/".into(),
        "--dev".into(),
        "/dev".into(),
        "--proc".into(),
        "/proc".into(),
        "--tmpfs".into(),
        "/tmp".into(),
        // No home directory. Full stop.
        "--tmpfs".into(),
        home.display().to_string(),
    ];

    // Mask the runtime dir (D-Bus session bus, Wayland socket, podman
    // control sockets, …), then bind back only the IDE's MCP socket.
    if let Ok(runtime_dir) = std::env::var("XDG_RUNTIME_DIR") {
        args.push("--tmpfs".into());
        args.push(runtime_dir);
    }
    if let Some(socket) = mcp_socket {
        args.push("--bind".into());
        args.push(socket.display().to_string());
        args.push(socket.display().to_string());
    }

    // Bind back only the agent's own auth/config/cache paths (if present).
    for rel in &spec.home_paths {
        let path = home.join(rel);
        if path.exists() {
            args.push("--bind".into());
            args.push(path.display().to_string());
            args.push(path.display().to_string());
        }
    }

    let root = workspace_root.display().to_string();
    if safe_mode {
        // Read everything (context for writing good config), write only the
        // safe-mode scope: devcontainer setup + workspace-ergonomics
        // dotfiles. (bwrap binds need existing targets; files not yet
        // created stay read-only until the user creates them.)
        args.push("--ro-bind".into());
        args.push(root.clone());
        args.push(root.clone());
        for scope in taste_core::policy::safe_mode_scope(workspace_root) {
            if scope.exists() {
                args.push("--bind".into());
                args.push(scope.display().to_string());
                args.push(scope.display().to_string());
            }
        }
    } else {
        args.push("--bind".into());
        args.push(root.clone());
        args.push(root.clone());
    }

    // Keep the agent from arming host-side git execution: hooks are masked
    // (its own commits see an empty hooks dir) and config is read-only (no
    // core.fsmonitor / hooksPath injection for the user's git to trip over).
    let git_dir = workspace_root.join(".git");
    if git_dir.join("hooks").is_dir() {
        args.push("--tmpfs".into());
        args.push(git_dir.join("hooks").display().to_string());
    }
    if git_dir.join("config").is_file() {
        args.push("--ro-bind".into());
        args.push(git_dir.join("config").display().to_string());
        args.push(git_dir.join("config").display().to_string());
    }

    // Sign-in flows: $BROWSER routes URLs to the IDE for user-confirmed
    // opening (xdg-open honors $BROWSER when no desktop portal is visible).
    if let Some((script, dir)) = url_bridge {
        args.push("--ro-bind".into());
        args.push(script.display().to_string());
        args.push(script.display().to_string());
        args.push("--bind".into());
        args.push(dir.display().to_string());
        args.push(dir.display().to_string());
        args.push("--setenv".into());
        args.push("BROWSER".into());
        args.push(script.display().to_string());
    }

    // Defense-in-depth push block (see module docs: credentials absence is
    // the real enforcement).
    args.push("--ro-bind".into());
    args.push(git_policy.display().to_string());
    args.push(git_policy.display().to_string());
    args.push("--setenv".into());
    args.push("GIT_CONFIG_GLOBAL".into());
    args.push(git_policy.display().to_string());

    args.push("--chdir".into());
    args.push(root);

    args.push("--".into());
    args.push(spec.command.clone());
    args.extend(spec.args.iter().cloned());

    ("bwrap".to_string(), args)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::builtin_agents;

    fn claude() -> AgentSpec {
        builtin_agents().remove(0)
    }

    fn wrap_args(safe: bool) -> Vec<String> {
        wrap(
            &claude(),
            Path::new("/work/p"),
            safe,
            Path::new("/home/u"),
            Path::new("/cache/gitpolicy"),
            Some(Path::new("/run/user/1/taste-mcp.sock")),
            None,
        )
        .1
    }

    #[test]
    fn url_bridge_binds_helper_and_sets_browser() {
        let (_, args) = wrap(
            &claude(),
            Path::new("/work/p"),
            false,
            Path::new("/home/u"),
            Path::new("/cache/gitpolicy"),
            None,
            Some((
                Path::new("/cache/taste-open-url"),
                Path::new("/cache/agent-urls"),
            )),
        );
        let joined = args.join(" ");
        assert!(joined.contains("--ro-bind /cache/taste-open-url /cache/taste-open-url"));
        assert!(joined.contains("--bind /cache/agent-urls /cache/agent-urls"));
        assert!(joined.contains("--setenv BROWSER /cache/taste-open-url"));
    }

    #[test]
    fn url_helper_script_writes_into_drop_dir() {
        let dir = tempfile::tempdir().unwrap();
        std::env::set_var("XDG_CACHE_HOME", dir.path());
        let (script, drop_dir) = ensure_url_bridge().unwrap();
        std::env::remove_var("XDG_CACHE_HOME");
        assert!(script.is_file());
        let content = std::fs::read_to_string(&script).unwrap();
        assert!(content.contains(&drop_dir.display().to_string()));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&script).unwrap().permissions().mode();
            assert_eq!(mode & 0o111, 0o111, "helper must be executable");
        }
    }

    #[test]
    fn home_is_tmpfs_in_every_mode() {
        for safe in [true, false] {
            let joined = wrap_args(safe).join(" ");
            assert!(joined.contains("--tmpfs /home/u"));
            assert!(joined.contains("--setenv GIT_CONFIG_GLOBAL /cache/gitpolicy"));
        }
    }

    #[test]
    fn runtime_dir_is_masked_but_mcp_socket_bound() {
        // XDG_RUNTIME_DIR is set in any session running these tests.
        let joined = wrap_args(false).join(" ");
        assert!(joined.contains("--bind /run/user/1/taste-mcp.sock /run/user/1/taste-mcp.sock"));
    }

    #[test]
    fn safe_mode_mounts_workspace_read_only() {
        let joined = wrap_args(true).join(" ");
        assert!(joined.contains("--ro-bind /work/p /work/p"));
        assert!(!joined.contains("--bind /work/p /work/p"));
    }

    #[test]
    fn container_mode_mounts_workspace_read_write() {
        let joined = wrap_args(false).join(" ");
        assert!(joined.contains("--bind /work/p /work/p"));
    }

    #[test]
    fn agent_command_comes_after_separator() {
        let spec = claude();
        let args = wrap_args(false);
        let sep = args.iter().position(|a| a == "--").unwrap();
        assert_eq!(args[sep + 1], spec.command);
        assert_eq!(&args[sep + 2..], spec.args.as_slice());
    }

    #[test]
    fn git_hooks_and_config_are_protected_when_present() {
        let dir = tempfile::tempdir().unwrap();
        let git = dir.path().join(".git");
        std::fs::create_dir_all(git.join("hooks")).unwrap();
        std::fs::write(git.join("config"), "[core]\n").unwrap();
        let (_, args) = wrap(
            &claude(),
            dir.path(),
            false,
            Path::new("/home/u"),
            Path::new("/cache/gitpolicy"),
            None,
            None,
        );
        let joined = args.join(" ");
        assert!(joined.contains(&format!("--tmpfs {}", git.join("hooks").display())));
        assert!(joined.contains(&format!(
            "--ro-bind {} {}",
            git.join("config").display(),
            git.join("config").display()
        )));
    }

    #[test]
    fn push_block_config_rewrites_push_urls_only() {
        assert!(GIT_PUSH_BLOCK.contains("pushInsteadOf = https://"));
        assert!(GIT_PUSH_BLOCK.contains("pushInsteadOf = git@"));
        // Fetch rewriting (insteadOf without the push prefix) must NOT appear.
        for line in GIT_PUSH_BLOCK.lines() {
            let trimmed = line.trim_start();
            if trimmed.starts_with("insteadOf") {
                panic!("policy must not rewrite fetch URLs: {line}");
            }
        }
    }
}
