//! Agent confinement via bubblewrap.
//!
//! Threat model: **neither the agent nor the project repo is trusted.**
//! Agents are siblings of the IDE (they must survive devcontainer reloads),
//! but they never get the host. Every agent subprocess runs under `bwrap`
//! with:
//!
//! - the OS visible read-only (toolchains, certs, DNS keep working),
//! - a tmpfs over `$HOME` — no general home-directory access, ever — with
//!   only the agent's own auth/config paths bound back in,
//! - a tmpfs over `$XDG_RUNTIME_DIR` and `/tmp`, hiding the session D-Bus
//!   socket (which could otherwise reach the Flatpak portal → host exec),
//!   the Wayland/X11 sockets, and everything else that lives there; only
//!   the IDE's MCP socket is bound back in,
//! - **no workspace**: a read-only stand-in at the workspace path (see
//!   [`ensure_workspace_stub`]) rather than the project itself. The agent
//!   reaches the workspace through the IDE — ACP `fs/read_text_file` and
//!   `fs/write_text_file` for contents, `ide_list_files`/`ide_search` to
//!   navigate, `ide_exec` to run things in the devcontainer,
//! - network shared (agents need their APIs; fetching public remotes works).
//!
//! Note what is NOT here any more: the mount set does not encode the mode.
//! Safe mode used to be baked in at spawn, so a session started in safe
//! mode stayed confined until it was restarted. Writes are now checked
//! against `taste_core::policy::write_allowed` when they are made, which is
//! both stricter (one rule, the same one the user's edits pass) and kinder
//! (the workspace unlocks for the session already running).
//!
//! Remote git is read-only by construction: the tmpfs home contains no ssh
//! keys and no credential helpers, so authenticated push is impossible, and
//! `taste-devcontainer::security` keeps any from being mounted into the
//! devcontainer where brokered commands run. The push-block config is
//! defense-in-depth and UX (a clear error instead of an auth prompt), not
//! the enforcement — an agent controls its own environment inside the
//! sandbox. Its single definition is
//! `taste_core::policy::agent_git_config`; this module renders it to a
//! file, `ExecContext::resolve_for_agent` renders it to environment.
//!
//! Known residual risk, accepted and documented: agents have network access,
//! so a hostile agent could exfiltrate *workspace contents*. Confinement
//! bounds what it can read to the workspace and its own config — not what
//! it can say.
//!
//! If bubblewrap is unavailable, agents do not launch. Confinement is not
//! best-effort.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::AgentSpec;

/// The agent git policy as a gitconfig file.
///
/// The policy itself lives in `taste_core::policy::agent_git_config` — the
/// same one `ExecContext::resolve_for_agent` passes as environment on
/// agent-brokered commands. Two renderings, one definition, so a scheme
/// added in one place cannot go missing in the other.
///
/// Each entry gets its own section block. Repeated sections are legal in
/// gitconfig and merging them would buy nothing but a bug surface.
fn git_policy_block() -> String {
    let mut out = String::from("# Generated by taste-ide: agents may fetch/pull but never push.\n");
    for (key, value) in taste_core::policy::agent_git_config() {
        // `section.subsection.key`: the first dot ends the section and the
        // last begins the key, so a subsection may contain dots (the
        // push-blocked URLs do).
        let (section, rest) = key.split_once('.').unwrap_or((key.as_str(), ""));
        match rest.rsplit_once('.') {
            Some((subsection, leaf)) => {
                out.push_str(&format!(
                    "[{section} {}]\n\t{leaf} = {value}\n",
                    gitconfig_quote(subsection)
                ));
            }
            None => out.push_str(&format!("[{section}]\n\t{rest} = {value}\n")),
        }
    }
    out
}

/// The policy file's contents: the push block, plus the host's identity
/// when it has one. `GIT_CONFIG_GLOBAL` REPLACES the global config, so
/// without this an agent has no `user.name`/`user.email` at all and its
/// commits die with "Author identity unknown". Identity is not a
/// credential — the same name and email ride on every commit the user
/// pushes.
fn git_policy_contents(identity: Option<&taste_git::GitIdentity>) -> String {
    let mut contents = git_policy_block();
    if let Some(identity) = identity {
        contents.push_str(&format!(
            "[user]\n\tname = {}\n\temail = {}\n",
            gitconfig_quote(&identity.name),
            gitconfig_quote(&identity.email),
        ));
    }
    contents
}

/// A gitconfig quoted value: backslashes and quotes escaped, newlines
/// dropped (a value cannot span lines, and an identity never needs one).
fn gitconfig_quote(value: &str) -> String {
    let cleaned: String = value
        .chars()
        .filter(|c| !matches!(c, '\n' | '\r'))
        .collect();
    format!("\"{}\"", cleaned.replace('\\', "\\\\").replace('"', "\\\""))
}

/// Where the push-block gitconfig lives; written once per run. Deliberately
/// *outside* `XDG_RUNTIME_DIR` (which is masked in the sandbox): it sits in
/// the IDE's cache dir and is bound in read-only.
pub fn ensure_git_policy_file() -> Result<PathBuf> {
    let base = cache_dir();
    std::fs::create_dir_all(&base).context("creating taste-ide cache dir")?;
    let path = base.join("agent-gitconfig");
    let contents = git_policy_contents(taste_git::host_identity().as_ref());
    std::fs::write(&path, contents).context("writing agent git policy file")?;
    Ok(path)
}

/// What an agent finds where the workspace used to be mounted.
///
/// The agent reaches the workspace through the IDE — ACP `fs/read_text_file`
/// and `fs/write_text_file` for contents, `ide_list_files`/`ide_search` to
/// navigate, `ide_exec` to run things in the devcontainer. So there is no
/// workspace bind, and an agent that reaches for `cat` finds this instead
/// of an empty directory it has to guess about.
const WORKSPACE_STUB_README: &str = "\
# The workspace is not here

taste-ide serves this workspace to you rather than mounting it. Almost
nothing under this path is real: it is a read-only stand-in so your
working directory exists. The exception is this project's own agent
instructions and settings (`AGENTS.md`, `CLAUDE.md`, `.claude/` and their
equivalents), which are here, read-only, because you need them before you
can ask for anything.

To work with the project:

- **Read a file**  — ACP `fs/read_text_file` (absolute paths). It answers
  from the user's open editor buffers, so you see their unsaved edits.
- **Write a file** — ACP `fs/write_text_file`. The IDE applies it, checks
  it against the write policy, and lands it in the buffer the user is
  looking at.
- **Find things**  — the `ide_list_files` and `ide_search` MCP tools; and
  `ide_references` for exact symbol references.
- **Run things**   — the `ide_exec` MCP tool. Your commands run in the
  project's devcontainer, which is where the toolchain and the real
  workspace are, and where the user's own builds run.

`ide_environment` explains the topology; `ide_write_policy` explains what
is writable right now and why.
";

/// Create the stand-in workspace directory and return it. Bound over the
/// workspace path in every agent sandbox.
///
/// Keyed by workspace, and *reconciled* rather than rebuilt: it carries
/// mount points for whatever agent-context files this workspace has (see
/// [`agent_context_binds`]), and a stale empty `CLAUDE.md` left from a
/// different project would be worse than none at all — an agent reads it
/// as "this project has no conventions".
///
/// Reconciled, not recreated, because sessions overlap. Two windows on one
/// workspace share a stub, and so do a new session and the one it
/// replaces; deleting the directory would pull it out from under an agent
/// already mounted on it. Concurrent calls for the same workspace compute
/// the same desired contents, so they cannot fight.
pub fn ensure_workspace_stub(workspace_root: &Path) -> Result<PathBuf> {
    stub_in(&cache_dir(), workspace_root)
}

/// [`ensure_workspace_stub`] against an explicit base directory. Split out
/// so tests need not touch `XDG_CACHE_HOME`, which is process-global and
/// therefore shared with every other test running at the same time.
fn stub_in(base: &Path, workspace_root: &Path) -> Result<PathBuf> {
    let dir = base
        .join("workspace-stub")
        .join(workspace_key(workspace_root));
    std::fs::create_dir_all(&dir).context("creating the workspace stub dir")?;
    std::fs::write(dir.join("README-taste-ide.md"), WORKSPACE_STUB_README)
        .context("writing the workspace stub README")?;

    // A bind needs its target to exist, and the stub mounts read-only, so
    // the mount points cannot be created after the fact. Make them now.
    let mut wanted = vec![PathBuf::from("README-taste-ide.md")];
    for (source, _) in agent_context_binds(workspace_root) {
        let Ok(relative) = source.strip_prefix(workspace_root) else {
            continue;
        };
        let target = dir.join(relative);
        if source.is_dir() {
            std::fs::create_dir_all(&target)
        } else {
            target
                .parent()
                .map_or(Ok(()), std::fs::create_dir_all)
                .and_then(|()| std::fs::write(&target, ""))
        }
        .with_context(|| format!("creating stub mount point {}", target.display()))?;
        // Only the top component: a mount point nested under a directory
        // that is itself a mount point is that directory's business.
        wanted.push(relative.components().take(1).collect());
    }

    // Drop what this workspace no longer wants — a context file the user
    // deleted must not keep answering as an empty one.
    for entry in std::fs::read_dir(&dir)
        .context("reading the workspace stub dir")?
        .flatten()
    {
        let name = PathBuf::from(entry.file_name());
        if wanted.contains(&name) {
            continue;
        }
        let path = entry.path();
        let _ = if path.is_dir() {
            std::fs::remove_dir_all(&path)
        } else {
            std::fs::remove_file(&path)
        };
    }
    Ok(dir)
}

/// A short, stable-enough name for a workspace. The directory it names is
/// rebuilt every spawn, so this only has to separate concurrent windows on
/// different workspaces — not survive a release.
fn workspace_key(workspace_root: &Path) -> String {
    use std::hash::{Hash, Hasher};
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    workspace_root.hash(&mut hasher);
    format!("{:016x}", hasher.finish())
}

/// The agent-context files this workspace actually has, as (source,
/// destination) pairs — the same path on both sides, since the workspace
/// mounts at its real location.
///
/// Read-only, always: see `taste_core::policy::agent_context_scope` for
/// why these are the one thing an agent may see without asking the IDE.
fn agent_context_binds(workspace_root: &Path) -> Vec<(PathBuf, PathBuf)> {
    taste_core::policy::agent_context_scope(workspace_root)
        .into_iter()
        .filter(|path| path.exists())
        .map(|path| (path.clone(), path))
        .collect()
}

/// The MCP stdio bridge, as a command that runs wherever the agent does.
///
/// The IDE binary path means nothing inside a container, so something in
/// there has to carry stdio to the unix socket. `socat` was the obvious
/// choice and is the wrong one once the agent runs in the PROJECT
/// devcontainer: that image belongs to the repo, and nothing puts socat in
/// it. `node` is guaranteed — the adapter cannot start without it — so the
/// bridge costs no dependency the agent does not already have.
///
/// Errors are reported and exit non-zero rather than hanging: an MCP
/// bridge that silently never connects looks to the model like an IDE with
/// no tools.
pub fn mcp_bridge_command(socket: &Path) -> (String, Vec<String>) {
    const BRIDGE: &str = "const net=require('net');\
         const s=net.connect(process.argv[1]);\
         process.stdin.pipe(s);s.pipe(process.stdout);\
         s.on('close',()=>process.exit(0));\
         s.on('error',e=>{console.error('mcp bridge: '+e.message);process.exit(1)});";
    (
        "node".to_string(),
        vec!["-e".into(), BRIDGE.into(), socket.display().to_string()],
    )
}

/// The URL bridge: how a sandboxed agent's sign-in flow reaches the user's
/// real browser. The sandbox has no D-Bus and no portal, so `xdg-open`
/// cannot work inside it — instead `$BROWSER` points at a helper that
/// writes the URL into a directory the IDE watches. The IDE confirms with
/// the user and opens it host-side. OAuth localhost callbacks work because
/// the sandbox shares the network namespace.
pub fn url_bridge_dir() -> PathBuf {
    cache_dir().join("agent-urls")
}

/// The IDE's cache directory: deliberately outside `XDG_RUNTIME_DIR`,
/// which every agent sandbox masks. The files bound into sandboxes from
/// here (git policy, URL helper, workspace stub) all live under it.
fn cache_dir() -> PathBuf {
    std::env::var("XDG_CACHE_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
            Path::new(&home).join(".cache")
        })
        .join("taste-ide")
}

/// Write the `$BROWSER` helper script and create the URL drop directory.
/// Returns (script path, drop dir).
pub fn ensure_url_bridge() -> Result<(PathBuf, PathBuf)> {
    let dir = url_bridge_dir();
    std::fs::create_dir_all(&dir).context("creating agent-urls dir")?;
    let script_path = dir
        .parent()
        .unwrap_or(Path::new("/tmp"))
        .join("taste-open-url");
    let script = format!(
        "#!/bin/sh\n# Generated by taste-ide: forwards URLs from sandboxed agents\n\
         # to the IDE, which confirms with the user before opening.\n\
         umask 077\nprintf '%s\\n' \"$1\" > \"{}/url-$$\"\n",
        dir.display()
    );
    std::fs::write(&script_path, script).context("writing url helper")?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&script_path, std::fs::Permissions::from_mode(0o755))
            .context("marking url helper executable")?;
    }
    Ok((script_path, dir))
}

/// True when the IDE itself runs inside a container (the self-hosting
/// bootstrap: taste-ide launched from its own devcontainer). bwrap cannot
/// nest in a rootless container, and it doesn't need to: the container is
/// the confinement — the user's real home is not mounted there at all.
pub fn inside_container() -> bool {
    Path::new("/run/.containerenv").exists() || Path::new("/.dockerenv").exists()
}

pub fn bwrap_available() -> bool {
    std::env::var_os("PATH")
        .map(|paths| std::env::split_paths(&paths).any(|dir| dir.join("bwrap").is_file()))
        .unwrap_or(false)
}

/// Wrap an agent command in the confinement sandbox.
///
/// `safe_mode` narrows workspace writes to the devcontainer scope.
/// `mcp_socket` is the one path under the masked runtime dir that is bound
/// back in, so the agent can reach the IDE's MCP server. The mount set is
/// fixed for the life of the process: a session spawned in safe mode keeps
/// safe-mode confinement until a new session is started.
/// Agent-in-a-container confinement: run the agent inside the project's
/// devcontainer image via (host) podman. Stronger than bwrap — no host
/// filesystem at all beyond the workspace and the IDE's bridge files —
/// and it is what makes the packaged Flatpak and bare-host runs work at
/// all: neither has node/npx installed.
///
/// Returns None when podman or the image is unavailable (bwrap fallback
/// applies). The availability probe runs once and is cached.
pub fn container_agent_command(
    spec: &AgentSpec,
    cwd: &Path,
    git_policy: &Path,
    workspace_stub: &Path,
    mcp_socket: Option<&Path>,
    url_bridge: (&Path, &Path),
    tty: bool,
) -> Option<(String, Vec<String>)> {
    static AVAILABLE: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    let image =
        std::env::var("TASTE_AGENT_IMAGE").unwrap_or_else(|_| "taste-ide-devcontainer".to_string());
    let sandboxed = Path::new("/.flatpak-info").exists();
    let available = *AVAILABLE.get_or_init(|| {
        let mut check = if sandboxed {
            let mut c = std::process::Command::new("flatpak-spawn");
            c.args(["--host", "podman", "image", "exists", &image]);
            c
        } else {
            let mut c = std::process::Command::new("podman");
            c.args(["image", "exists", &image]);
            c
        };
        check
            .status()
            .map(|status| status.success())
            .unwrap_or(false)
    });
    if !available {
        return None;
    }
    Some(container_agent_args(
        spec,
        cwd,
        git_policy,
        workspace_stub,
        mcp_socket,
        url_bridge,
        tty,
        image,
        sandboxed,
    ))
}

/// The pure command-line assembly behind [`container_agent_command`],
/// split out so tests can check the composed args without a podman probe.
#[allow(clippy::too_many_arguments)]
fn container_agent_args(
    spec: &AgentSpec,
    cwd: &Path,
    git_policy: &Path,
    workspace_stub: &Path,
    mcp_socket: Option<&Path>,
    url_bridge: (&Path, &Path),
    tty: bool,
    image: String,
    sandboxed: bool,
) -> (String, Vec<String>) {
    let mut args: Vec<String> = Vec::new();
    if sandboxed {
        args.extend(["--host".into(), "podman".into()]);
    }
    args.extend(
        [
            "run",
            "--rm",
            "-i",
            "--userns=keep-id:uid=1000,gid=1000",
            "--security-opt",
            "label=disable",
            // OAuth callbacks reach the login flow.
            "--network=host",
            // Sign-ins persist across sessions, isolated from the real home.
            "-v",
            "taste-agent-home:/home/dev",
            "-e",
            "HOME=/home/dev",
        ]
        .map(String::from),
    );
    if tty {
        // Login TUIs run in a console tab (a real pty): give the container
        // a terminal so raw-mode prompts work.
        args.push("-t".into());
    }
    // NOT the workspace: a read-only stand-in, so the agent's working
    // directory exists and paths it exchanges with the IDE still mean the
    // same thing on both sides — while the only route to the project's
    // actual contents is through the IDE. See `ensure_workspace_stub`.
    args.push("-v".into());
    args.push(format!("{}:{}:ro", workspace_stub.display(), cwd.display()));
    // ...except the agent's own instructions and settings, read-only, on
    // top of the stand-in. Podman orders nested mounts by destination
    // depth, so these land after the stub they sit inside.
    for (source, destination) in agent_context_binds(cwd) {
        args.push("-v".into());
        args.push(format!("{}:{}:ro", source.display(), destination.display()));
    }
    args.push("-w".into());
    args.push(cwd.display().to_string());
    args.push("-v".into());
    args.push(format!(
        "{}:{}:ro",
        git_policy.display(),
        git_policy.display()
    ));
    args.push("-e".into());
    args.push(format!("GIT_CONFIG_GLOBAL={}", git_policy.display()));
    if let Some(socket) = mcp_socket {
        args.push("-v".into());
        args.push(format!("{}:{}", socket.display(), socket.display()));
    }
    let (url_script, url_dir) = url_bridge;
    args.push("-v".into());
    args.push(format!("{}:{}", url_dir.display(), url_dir.display()));
    args.push("-v".into());
    args.push(format!(
        "{}:{}:ro",
        url_script.display(),
        url_script.display()
    ));
    args.push("-e".into());
    args.push(format!("BROWSER={}", url_script.display()));
    // The environment announces itself: any process in this container —
    // MCP-aware or a bare `env` in a shell — can see it runs under
    // taste-ide and HOW it is confined, instead of reverse-engineering
    // the topology from /proc (which shows only this container).
    args.push("-e".into());
    args.push(format!("TASTE_IDE_VERSION={}", env!("CARGO_PKG_VERSION")));
    args.push("-e".into());
    args.push("TASTE_IDE_CONFINEMENT=container".into());
    for (key, value) in &spec.env {
        args.push("-e".into());
        args.push(format!("{key}={value}"));
    }
    args.push(image);
    args.push(spec.command.clone());
    args.extend(spec.args.iter().cloned());
    let program = if sandboxed { "flatpak-spawn" } else { "podman" };
    (program.to_string(), args)
}

pub fn wrap(
    spec: &AgentSpec,
    workspace_root: &Path,
    workspace_stub: &Path,
    home: &Path,
    git_policy: &Path,
    mcp_socket: Option<&Path>,
    url_bridge: Option<(&Path, &Path)>,
) -> (String, Vec<String>) {
    let mut args: Vec<String> = vec![
        "--die-with-parent".into(),
        "--unshare-pid".into(),
        // OS read-only: node, git, certs, resolv.conf all keep working.
        "--ro-bind".into(),
        "/".into(),
        "/".into(),
        "--dev".into(),
        "/dev".into(),
        "--proc".into(),
        "/proc".into(),
        "--tmpfs".into(),
        "/tmp".into(),
        // No home directory. Full stop.
        "--tmpfs".into(),
        home.display().to_string(),
    ];

    // Mask the runtime dir (D-Bus session bus, Wayland socket, podman
    // control sockets, …), then bind back only the IDE's MCP socket.
    if let Ok(runtime_dir) = std::env::var("XDG_RUNTIME_DIR") {
        args.push("--tmpfs".into());
        args.push(runtime_dir);
    }
    if let Some(socket) = mcp_socket {
        args.push("--bind".into());
        args.push(socket.display().to_string());
        args.push(socket.display().to_string());
    }

    // Bind back only the agent's own auth/config/cache paths (if present).
    for rel in &spec.home_paths {
        let path = home.join(rel);
        if path.exists() {
            args.push("--bind".into());
            args.push(path.display().to_string());
            args.push(path.display().to_string());
        }
    }

    // The workspace is NOT here — a read-only stand-in occupies its path so
    // the agent has a working directory that means the same thing on both
    // sides. Everything real goes through the IDE.
    //
    // Note what this removes: the mount set no longer encodes the MODE.
    // Safe mode used to be baked in at spawn, so a session started in safe
    // mode stayed confined until it was restarted. Now every write is
    // checked against `taste_core::policy::write_allowed` when it is made,
    // so bringing the devcontainer up unlocks the workspace for the
    // session already running.
    let root = workspace_root.display().to_string();
    args.push("--ro-bind".into());
    args.push(workspace_stub.display().to_string());
    args.push(root.clone());

    // ...except the agent's own instructions and settings. Ordered after
    // the stand-in they sit inside: bwrap applies binds in argument order.
    for (source, destination) in agent_context_binds(workspace_root) {
        args.push("--ro-bind".into());
        args.push(source.display().to_string());
        args.push(destination.display().to_string());
    }

    // Sign-in flows: $BROWSER routes URLs to the IDE for user-confirmed
    // opening (xdg-open honors $BROWSER when no desktop portal is visible).
    if let Some((script, dir)) = url_bridge {
        args.push("--ro-bind".into());
        args.push(script.display().to_string());
        args.push(script.display().to_string());
        args.push("--bind".into());
        args.push(dir.display().to_string());
        args.push(dir.display().to_string());
        args.push("--setenv".into());
        args.push("BROWSER".into());
        args.push(script.display().to_string());
    }

    // Defense-in-depth push block (see module docs: credentials absence is
    // the real enforcement).
    args.push("--ro-bind".into());
    args.push(git_policy.display().to_string());
    args.push(git_policy.display().to_string());
    args.push("--setenv".into());
    args.push("GIT_CONFIG_GLOBAL".into());
    args.push(git_policy.display().to_string());

    // The environment announces itself (see container_agent_command).
    args.push("--setenv".into());
    args.push("TASTE_IDE_VERSION".into());
    args.push(env!("CARGO_PKG_VERSION").into());
    args.push("--setenv".into());
    args.push("TASTE_IDE_CONFINEMENT".into());
    args.push("bwrap".into());

    // The spec's own environment, explicitly. It would arrive by
    // inheritance anyway (bwrap is not given `--clearenv`), but the
    // container path passes it as `-e` flags and the two should not
    // disagree about where an agent's environment comes from.
    for (key, value) in &spec.env {
        args.push("--setenv".into());
        args.push(key.clone());
        args.push(value.clone());
    }

    args.push("--chdir".into());
    args.push(root);

    args.push("--".into());
    args.push(spec.command.clone());
    args.extend(spec.args.iter().cloned());

    ("bwrap".to_string(), args)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::builtin_agents;

    fn claude() -> AgentSpec {
        builtin_agents().remove(0)
    }

    #[test]
    fn policy_file_carries_the_push_block_and_identity() {
        let identity = taste_git::GitIdentity {
            name: r#"Ada "the" Love\lace"#.into(),
            email: "ada@example.com".into(),
        };
        let contents = git_policy_contents(Some(&identity));
        assert!(contents.contains("pushInsteadOf"));
        assert!(contents.contains(r#"name = "Ada \"the\" Love\\lace""#));
        assert!(contents.contains(r#"email = "ada@example.com""#));
        // Without an identity, nothing pretends to be one.
        assert!(!git_policy_contents(None).contains("[user]"));
    }

    #[test]
    fn gitconfig_quote_strips_newlines() {
        assert_eq!(gitconfig_quote("a\nb\r"), "\"ab\"");
    }

    fn wrap_args() -> Vec<String> {
        wrap(
            &claude(),
            Path::new("/work/p"),
            Path::new("/cache/workspace-stub"),
            Path::new("/home/u"),
            Path::new("/cache/gitpolicy"),
            Some(Path::new("/run/user/1/taste-mcp.sock")),
            None,
        )
        .1
    }

    #[test]
    fn container_agent_args_keep_flags_paired() {
        // Regression: "--security-opt" once lost its "label=disable"
        // value, and podman parsed the value as the image (exit 125).
        let spec = AgentSpec::new("test", "Test", "npx", &["agent"], &[]);
        let cwd = Path::new("/work/project");
        let policy = Path::new("/tmp/gitpolicy");
        let bridge = (Path::new("/tmp/url.sh"), Path::new("/tmp/urldrop"));
        for tty in [false, true] {
            let (program, args) = container_agent_args(
                &spec,
                cwd,
                policy,
                Path::new("/cache/workspace-stub"),
                None,
                bridge,
                tty,
                "test-image".into(),
                false,
            );
            assert_eq!(program, "podman");
            for (index, arg) in args.iter().enumerate() {
                for flag in ["--security-opt", "-v", "-e", "-w"] {
                    if arg == flag {
                        let value = args
                            .get(index + 1)
                            .unwrap_or_else(|| panic!("{flag} at end of args: {args:?}"));
                        assert!(
                            !value.starts_with('-'),
                            "{flag} followed by flag {value}: {args:?}"
                        );
                    }
                }
            }
            assert!(args.iter().any(|a| a == "label=disable"));
            let pos = args.iter().position(|a| a == "label=disable").unwrap();
            assert_eq!(args[pos - 1], "--security-opt");
            assert_eq!(args.iter().any(|a| a == "-t"), tty);
            // The image comes right before the agent command.
            let image = args.iter().position(|a| a == "test-image").unwrap();
            assert_eq!(args[image + 1], "npx");
        }
    }

    /// The bridge has to run in the PROJECT devcontainer once the agent
    /// moves there, and that image belongs to the repo. node is the one
    /// interpreter guaranteed to be present, because the adapter is a
    /// node program — so depending on it costs nothing that was optional.
    #[test]
    fn the_mcp_bridge_depends_only_on_node() {
        let (program, args) = mcp_bridge_command(Path::new("/run/user/1000/taste-mcp.sock"));
        assert_eq!(program, "node");
        assert_eq!(args[0], "-e");
        assert_eq!(args[2], "/run/user/1000/taste-mcp.sock");
        // Both directions, or the agent talks and never hears back.
        assert!(args[1].contains("process.stdin.pipe(s)"), "{}", args[1]);
        assert!(args[1].contains("s.pipe(process.stdout)"), "{}", args[1]);
        // A bridge that cannot connect must SAY so: silence reads to the
        // model as an IDE with no tools.
        assert!(args[1].contains("error"), "{}", args[1]);
        assert!(!args[1].contains("socat"));
    }

    #[test]
    fn url_bridge_binds_helper_and_sets_browser() {
        let (_, args) = wrap(
            &claude(),
            Path::new("/work/p"),
            Path::new("/cache/workspace-stub"),
            Path::new("/home/u"),
            Path::new("/cache/gitpolicy"),
            None,
            Some((
                Path::new("/cache/taste-open-url"),
                Path::new("/cache/agent-urls"),
            )),
        );
        let joined = args.join(" ");
        assert!(joined.contains("--ro-bind /cache/taste-open-url /cache/taste-open-url"));
        assert!(joined.contains("--bind /cache/agent-urls /cache/agent-urls"));
        assert!(joined.contains("--setenv BROWSER /cache/taste-open-url"));
    }

    /// The auth proxy injects through `spec.env` and nothing else, so
    /// every confinement has to turn that into real process environment —
    /// otherwise the agent silently keeps talking to the API directly.
    #[test]
    fn the_specs_environment_reaches_every_confinement() {
        let mut spec = claude();
        spec.env
            .push(("ANTHROPIC_BASE_URL".into(), "http://127.0.0.1:41234".into()));
        spec.env
            .push(("ANTHROPIC_AUTH_TOKEN".into(), "sk-ant-taste-abc".into()));

        let (_, bwrap_args) = wrap(
            &spec,
            Path::new("/work/p"),
            Path::new("/cache/workspace-stub"),
            Path::new("/home/u"),
            Path::new("/cache/gitpolicy"),
            None,
            None,
        );
        let joined = bwrap_args.join(" ");
        assert!(joined.contains("--setenv ANTHROPIC_BASE_URL http://127.0.0.1:41234"));
        assert!(joined.contains("--setenv ANTHROPIC_AUTH_TOKEN sk-ant-taste-abc"));
        // ...and before the `--` that ends bwrap's own arguments.
        let separator = bwrap_args.iter().position(|a| a == "--").unwrap();
        let token = bwrap_args
            .iter()
            .position(|a| a == "sk-ant-taste-abc")
            .unwrap();
        assert!(token < separator);

        let (_, container_args) = container_agent_args(
            &spec,
            Path::new("/work/p"),
            Path::new("/cache/gitpolicy"),
            Path::new("/cache/workspace-stub"),
            None,
            (Path::new("/tmp/url.sh"), Path::new("/tmp/urldrop")),
            false,
            "test-image".into(),
            false,
        );
        let joined = container_args.join(" ");
        assert!(joined.contains("-e ANTHROPIC_BASE_URL=http://127.0.0.1:41234"));
        assert!(joined.contains("-e ANTHROPIC_AUTH_TOKEN=sk-ant-taste-abc"));
        // ...and before the image, or podman reads them as the command.
        let image = container_args.iter().position(|a| a == "test-image").unwrap();
        let token = container_args
            .iter()
            .position(|a| a == "ANTHROPIC_AUTH_TOKEN=sk-ant-taste-abc")
            .unwrap();
        assert!(token < image);
    }

    #[test]
    fn url_helper_script_writes_into_drop_dir() {
        let dir = tempfile::tempdir().unwrap();
        std::env::set_var("XDG_CACHE_HOME", dir.path());
        let (script, drop_dir) = ensure_url_bridge().unwrap();
        std::env::remove_var("XDG_CACHE_HOME");
        assert!(script.is_file());
        let content = std::fs::read_to_string(&script).unwrap();
        assert!(content.contains(&drop_dir.display().to_string()));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&script).unwrap().permissions().mode();
            assert_eq!(mode & 0o111, 0o111, "helper must be executable");
        }
    }

    #[test]
    fn home_is_tmpfs_and_the_environment_announces_itself() {
        let joined = wrap_args().join(" ");
        assert!(joined.contains("--tmpfs /home/u"));
        assert!(joined.contains("--setenv GIT_CONFIG_GLOBAL /cache/gitpolicy"));
        // The environment announces itself in every confinement.
        assert!(joined.contains("--setenv TASTE_IDE_CONFINEMENT bwrap"));
        assert!(joined.contains("--setenv TASTE_IDE_VERSION"));
    }

    #[test]
    fn runtime_dir_is_masked_but_mcp_socket_bound() {
        // XDG_RUNTIME_DIR is set in any session running these tests.
        let joined = wrap_args().join(" ");
        assert!(joined.contains("--bind /run/user/1/taste-mcp.sock /run/user/1/taste-mcp.sock"));
    }

    /// The whole point of the mediated topology: the agent's process has
    /// no workspace. Not read-only, not partly — the project's bytes are
    /// not on the other side of any mount it holds.
    #[test]
    fn the_workspace_is_not_mounted_only_a_stand_in() {
        let joined = wrap_args().join(" ");
        assert!(
            joined.contains("--ro-bind /cache/workspace-stub /work/p"),
            "{joined}"
        );
        assert!(
            !joined.contains("--bind /work/p /work/p"),
            "the workspace itself must not be bound: {joined}"
        );
        // And it still has somewhere to be.
        assert!(joined.contains("--chdir /work/p"), "{joined}");
    }

    /// The mode is no longer baked into the mount set, so bringing the
    /// devcontainer up unlocks the workspace for the session already
    /// running instead of the next one.
    #[test]
    fn confinement_does_not_encode_the_mode() {
        let joined = wrap_args().join(" ");
        for scope in taste_core::policy::safe_mode_scope(Path::new("/work/p")) {
            assert!(
                !joined.contains(&scope.display().to_string()),
                "the safe-mode scope must not appear in the mount set: {joined}"
            );
        }
    }

    /// The one thing the agent may see without asking the IDE: its own
    /// instructions. An agent that arrives without them does not know the
    /// project's conventions, and this project's whole steering mechanism
    /// is a file in the workspace root.
    #[test]
    fn agent_context_files_are_bound_read_only_over_the_stand_in() {
        let cache = tempfile::tempdir().unwrap();
        let workspace = tempfile::tempdir().unwrap();
        let root = workspace.path();
        std::fs::write(root.join("CLAUDE.md"), "# rules of the road\n").unwrap();
        std::fs::create_dir_all(root.join(".claude")).unwrap();
        std::fs::write(root.join("src.rs"), "fn main() {}\n").unwrap();

        let stub = stub_in(cache.path(), root).unwrap();
        // A bind needs its target to exist inside the read-only stand-in.
        assert!(
            stub.join("CLAUDE.md").is_file(),
            "no mount point for CLAUDE.md"
        );
        assert!(stub.join(".claude").is_dir(), "no mount point for .claude");
        assert!(stub.join("README-taste-ide.md").is_file());
        // Only mount points and the README — not the project.
        assert!(
            !stub.join("src.rs").exists(),
            "the project leaked into the stub"
        );

        let (_, args) = wrap(
            &claude(),
            root,
            &stub,
            Path::new("/home/u"),
            Path::new("/cache/gitpolicy"),
            None,
            None,
        );
        let joined = args.join(" ");
        let claude_md = root.join("CLAUDE.md");
        assert!(
            joined.contains(&format!(
                "--ro-bind {} {}",
                claude_md.display(),
                claude_md.display()
            )),
            "{joined}"
        );
        // Read-only, always: an agent must not rewrite its own instructions.
        assert!(
            !joined.contains(&format!("--bind {} ", claude_md.display())),
            "agent context must never be writable: {joined}"
        );
        // Nested inside the stand-in, so it has to be applied after it.
        let stub_at = args.iter().position(|a| a == &stub.display().to_string());
        let context_at = args
            .iter()
            .position(|a| a == &claude_md.display().to_string());
        assert!(
            stub_at < context_at,
            "context bind must follow the stand-in"
        );
        // And the project itself is still not there.
        assert!(
            !joined.contains(&format!("--bind {} {}", root.display(), root.display())),
            "{joined}"
        );
    }

    /// The stub is keyed by workspace and rebuilt each spawn: a CLAUDE.md
    /// left behind by another project would read as "this project has no
    /// conventions", which is worse than an agent knowing it has none.
    #[test]
    fn a_workspace_without_context_files_gets_no_stale_ones() {
        let cache = tempfile::tempdir().unwrap();
        let with = tempfile::tempdir().unwrap();
        std::fs::write(with.path().join("CLAUDE.md"), "# rules\n").unwrap();
        let without = tempfile::tempdir().unwrap();

        let populated = stub_in(cache.path(), with.path()).unwrap();
        let bare = stub_in(cache.path(), without.path()).unwrap();
        assert_ne!(
            populated, bare,
            "stubs must not be shared across workspaces"
        );
        assert!(populated.join("CLAUDE.md").exists());
        assert!(
            !bare.join("CLAUDE.md").exists(),
            "an empty CLAUDE.md is a lie an agent will believe"
        );
        assert!(agent_context_binds(without.path()).is_empty());

        // Rebuilt, not accumulated: dropping the file clears the stub.
        std::fs::remove_file(with.path().join("CLAUDE.md")).unwrap();
        let rebuilt = stub_in(cache.path(), with.path()).unwrap();
        assert!(!rebuilt.join("CLAUDE.md").exists());
    }

    #[test]
    fn agent_command_comes_after_separator() {
        let spec = claude();
        let args = wrap_args();
        let sep = args.iter().position(|a| a == "--").unwrap();
        assert_eq!(args[sep + 1], spec.command);
        assert_eq!(&args[sep + 2..], spec.args.as_slice());
    }

    #[test]
    fn push_block_config_rewrites_push_urls_only() {
        let block = git_policy_block();
        assert!(block.contains("pushInsteadOf = https://"), "{block}");
        assert!(block.contains("pushInsteadOf = git@"), "{block}");
        // Fetch rewriting (insteadOf without the push prefix) must NOT appear.
        for line in block.lines() {
            let trimmed = line.trim_start();
            if trimmed.starts_with("insteadOf") {
                panic!("policy must not rewrite fetch URLs: {line}");
            }
        }
    }

    /// The file rendering and the environment rendering are the same
    /// policy; a scheme blocked in one must be blocked in the other.
    #[test]
    fn the_file_rendering_covers_every_entry_of_the_shared_policy() {
        let block = git_policy_block();
        for (key, value) in taste_core::policy::agent_git_config() {
            let leaf = key.rsplit_once('.').map(|(_, l)| l).unwrap_or(&key);
            assert!(
                block.contains(&format!("{leaf} = {value}")),
                "{key}={value} missing from the file rendering:\n{block}"
            );
        }
        // A subsection with dots and slashes must survive quoting.
        assert!(block.contains(r#"[url "push-blocked-0://"]"#), "{block}");
    }
}
